export const topics = [
  'Bullying',
  'Health',
  'Daily Life',
  'School Life',
  'Family',
  'Office Life',
  'Religion',
  'Studies',
  'College Life',
  'Music',
  'Movies',
  'General',
  'Quotes',
  'Others',
  'Friends',
  'Mental Health',
  'Careers',
  'Jobs/Work',
  'General Arts',
  'Self-made Arts',
  'Sensitive Topics',
  'Parenting',
  'Advice',
  'Ideas',
  'My Story',
  'Venting',
  'Mental Disorders',
  'Mental Illness',
  'Life Story',
  'Random Feelings',
  'Relationships',
  'Eating Disorders',
  'Positive Arts',
  'Negative Arts',
  'Arts which show my stories',
  'Arts for Struggling emotions',
  'Arts which I like',
  'I need someone',
  'to chat with',
  'Just Chilling Here',
];

export const moods = {
  'Positive': [
    'Supportive',
    'Caring',
    'Glad',
    'Inspired',
    'Proud',
    'Hopeful',
    'Supported',
    'Positive',
    'Excited',
    'Amazed',
    'Happy',
    'Nostalgic',
  ],
  'Negative': [
    'Frustrated',
    'Angry',
    'Annoyed',
    'Sad',
    'Failure',
    'Disgusted',
    'Jealous',
    'Moody',
    'Irritated',
    'Misfit',
    'Struggling',
    'Negative',
  ],
  'Neutral': [
    'Neutral',
    'Shocked',
    'Dazed',
    'Bored',
    'Wandering',
    'Nothing',
    'Chilled',
    'Thinking',
    'Calm',
    'Relaxed',
    'Confused',
    'Uncertain',
  ],
  'Crisis': [
    'Lost',
    'Empty',
    'Numb',
    'Anxious',
    'Insecure',
    'Ashamed',
    'Suffocated',
    'Trapped',
    'Scattered',
    'Depressed',
    'Crisis',
    'Overwhelmed',
  ],
};